services:
  database:
    image: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: taskManagementSystem

  service:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/taskManagementSystem
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8090:8090"
    depends_on:
      - database


networks:
  app-network:
    driver: bridge