spring:
    application:
        name: TaskManagementSystem


    datasource:
        url: jdbc:postgresql://localhost:5433/taskManagementSystem
        username: user
        password: 123
    jpa:
        show-sql: true
    sql:
        init:
            schema-locations: classpath:/database/schema.sql
            data-locations: classpath:/database/data.sql
            mode: always

server:
    port: 8090

